parameters:
    # Clé par défaut pour le développement si la variable d'env n'est pas définie
    env(JWT_SECRET_KEY): 'Gabagool'

lexik_jwt_authentication:
    secret_key: '%env(string:JWT_SECRET_KEY)%'
    encoder:
        signature_algorithm: HS256
    token_ttl: 3600
